# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ik.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08ik.proto\"\x1d\n\tIKRequest\x12\x10\n\x08position\x18\x01 \x03(\x02\"\x1c\n\nIKResponse\x12\x0e\n\x06\x61ngles\x18\x01 \x03(\x02\x32\x39\n\tIKService\x12,\n\x0f\x43\x61lculateAngles\x12\n.IKRequest\x1a\x0b.IKResponse\"\x00\x62\x06proto3')



_IKREQUEST = DESCRIPTOR.message_types_by_name['IKRequest']
_IKRESPONSE = DESCRIPTOR.message_types_by_name['IKResponse']
IKRequest = _reflection.GeneratedProtocolMessageType('IKRequest', (_message.Message,), {
  'DESCRIPTOR' : _IKREQUEST,
  '__module__' : 'ik_pb2'
  # @@protoc_insertion_point(class_scope:IKRequest)
  })
_sym_db.RegisterMessage(IKRequest)

IKResponse = _reflection.GeneratedProtocolMessageType('IKResponse', (_message.Message,), {
  'DESCRIPTOR' : _IKRESPONSE,
  '__module__' : 'ik_pb2'
  # @@protoc_insertion_point(class_scope:IKResponse)
  })
_sym_db.RegisterMessage(IKResponse)

_IKSERVICE = DESCRIPTOR.services_by_name['IKService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IKREQUEST._serialized_start=12
  _IKREQUEST._serialized_end=41
  _IKRESPONSE._serialized_start=43
  _IKRESPONSE._serialized_end=71
  _IKSERVICE._serialized_start=73
  _IKSERVICE._serialized_end=130
# @@protoc_insertion_point(module_scope)
