# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ik_pb2 as ik__pb2


class IKServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateAngles = channel.unary_unary(
                '/IKService/CalculateAngles',
                request_serializer=ik__pb2.IKRequest.SerializeToString,
                response_deserializer=ik__pb2.IKResponse.FromString,
                )


class IKServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculateAngles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IKServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateAngles': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateAngles,
                    request_deserializer=ik__pb2.IKRequest.FromString,
                    response_serializer=ik__pb2.IKResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IKService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IKService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculateAngles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/IKService/CalculateAngles',
            ik__pb2.IKRequest.SerializeToString,
            ik__pb2.IKResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
